#pragma once
#include <GL/glew.h>

namespace dj
{

#define SERIALIZATION_GLENUM_LIST \
	ENTRY_GLENUM(GL_FRAMEBUFFER_COMPLETE) \
	ENTRY_GLENUM(GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT) \
	ENTRY_GLENUM(GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT) \
	ENTRY_GLENUM(GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER) \
	ENTRY_GLENUM(GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER) \
	ENTRY_GLENUM(GL_FRAMEBUFFER_UNSUPPORTED) \
	ENTRY_GLENUM(GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE) \
	ENTRY_GLENUM(GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS) \
	ENTRY_GLENUM(GL_FRAMEBUFFER_UNDEFINED) \
	ENTRY_GLENUM(GL_INVALID_ENUM)

#define ENTRY_GLENUM(glen) case glen: return #glen;
constexpr const char* toString(GLenum glenum)
{
	switch (glenum)
	{
		SERIALIZATION_GLENUM_LIST
	}
	return "Unknown enum";
}
#undef ENTRY_GLENUM

} // namespace dj